pool:
  name: Azure Pipelines
resources:
  repositories:
    - repository: AzureRepo
      type: git
      endpoint: ado-token
      name: project1/project1
      ref: main

jobs:
  - job: testcheckout
    steps:
      - checkout: AzureRepo
        
